version: '3.8'

services:
  develop:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
      args:
        - TZ=Asia/Shanghai
        - NODE_MAJOR=20 # 16 18 20 21 or empty
        - PYTHON_MAJOR=3 # 2 3 or empty
        - JDK_MAJOR=17 # 8 11 17 18 19 20 21 or empty
        - ODOO_VERSION=16.0 # 16.0 or empty, only support 16.0 now
    expose:
      - 22
    ports:
      - 10022:22
    volumes:
      - develop-data:/home/ubuntu
      - ~/.ssh:/home/ubuntu/.ssh
      - ~/.gitconfig:/home/ubuntu/.gitconfig
    environment:
      - TZ=Asia/Shanghai

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo

volumes:
  develop-data:
  postgres-data:
