version: '3.8'

services:
  develop:
    build:
      context: ..
      dockerfile: Dockerfile
      target: ubuntu
    expose:
      - 22
    ports:
      - 10022:22
    volumes:
      - ~/.ssh/authorized_keys:/home/ubuntu/.ssh/authorized_keys:ro
