version: '3.8'

services:
  develop:
    build:
      context: ..
      dockerfile: Dockerfile
      target: ubuntu
    expose:
      - 22
    ports:
      - 10022:22
    volumes:
      - ~/.ssh/authorized_keys:/home/ubuntu/.ssh/authorized_keys:ro

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data: